classdef PropertyEnum < Simulink.IntEnumType
% $Revision$
% $Author$
% $Date$
% $HeadURL$
	enumeration
		DENSITY(1)
		HEAT_CAPACITY(2)
		THERMAL_CONDUCTIVITY(3)
		VISCOSITY(4)
		ENTHALPY(5)
		ENTROPY(6)
		PRANDTL(7)
		SPECIFIC_VOLUME(8)
		EVAPORATION_ENTHALPY(9)
		VAPOURPRESSURE(10)
		SATURATIONTEMPERATURE(11)
		SATURATIONPROPERTY(12)
		TEMPERATURE_CONDUCTIVITY(13)
		ENTHALPY2TEMPERATURE(14)
		GRASHOFNUMBER(15)
		PRANDTLNUMBER(16)
		VAPOURCONTENT(17)
    end
end